dates:
  start: 2020-01-01 12:00:00
  end: 2020-12-27 12:00:00
  frequency: 12h

datastores:
  stretched-512-final:
    type: anemoi-inference
    path: /scratch/project_465001235/vandenbl/anemoi/experiments/inference/stretched_512_final/outputs/{yyyy}{mm}{dd}{HH}.nc
    mapping: cerra

  cerra:
    type: anemoi-datasets
    path: /scratch/project_465001235/datasets/cerra-rr-an-oper-0001-mars-5p5km-1984-2020-3h-v2-rmi.zarr
    mapping: cerra
  
  alaro-4km:
    type: rmi-re-pytools-fc
    path: /scratch/project_465001235/datasets/INDRA_2020_v2.nc
    model: ALO4
    station_info: /scratch/project_465001235/vanginde/rmai-verification/configs/INDRA.yaml

  IFS-HRES:
    type: rmi-re-pytools-fc
    path: /scratch/project_465001235/datasets/INDRA_2020_v2.nc
    model: ECDET
    station_info: /scratch/project_465001235/vanginde/rmai-verification/configs/INDRA.yaml
    
  SYNOP:
    type: rmi-re-pytools-obs
    path: /scratch/project_465001235/datasets/INDRA_2020_v2.nc
    model: OBS
    station_info: /scratch/project_465001235/vanginde/rmai-verification/configs/INDRA.yaml

transformations:
  rename:
    rename_dict:
      2t: [2t_2, T2M ]
      10u: [10u_10, U10M]
      10v: [10v_10, V10M]
      10s: [S10M, 10s_10]
      msl: [msl_0, MLSP]
  uv_to_speed:
    datastores:
      - stretched-512-final
      - cerra
    u: 10u
    v: 10v
    speed: 10s
  kelvin_to_celcius:
    datastores:
      - stretched-512-final
      - cerra
    fields: [2t]

interpolation:
  type: delaunay



verification:
  reference_datastore: SYNOP    
  interpolation: 
    type: delaunay

  variables : [2t, 10s]
  clusters:
    temporal:
      package : xskillscore
      metrics:
        - mse
        - bias
        - rmse
      avg_dims: [code, reference_time]

output:
  type: netcdf
  temporal:
    path: ./ANEMOIvALO4vIFSHRES.nc

visualization:
  temporal:
    directory: "./"
    prefix: "STRETCHEDvALO4vIFSHRESvCERRA"
    x: "lead_time"
    
 

    
  
    
